language: node_js
node_js:
  - "5.3"
before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - psql -c 'create database test;' -U postgres
  - psql "dbname=test options=--search_path=public" -f db/fwibble.sql

  # - npm run migrate
addons:
  - postgresql: "9.3"
services:
  - postgresql

notifications: 
  email: false